spring:
  application:
    name: EUREKA-HA

server:
  port: 8081

eureka:
  #server:
  #enable-self-preservation: false
  #eviction-interval-timer-in-ms: 5000
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
